import rtconfig
from building import *
import os

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

if GetDepend(['BSP_USING_FREERTOS']):
    objs = objs + SConscript('abstraction-rtos/SConscript')

if GetDepend(['BSP_USB_ROLE_HOST_UVC']):
    objs = objs + SConscript('emusb-host/SConscript')

if GetDepend('PKG_USING_CHERRYUSB') or GetDepend('RT_USING_CHERRYUSB'):
    objs = objs + SConscript('CherryUSB-1.6.0/SConscript')

if GetDepend(['RT_USING_WIFI_HOST_DRIVER']):
    objs = objs + SConscript('wifi-host-driver/SConscript')

Return('objs')
