import os

Import('RTT_ROOT')
Import('rtconfig')
Import('env')
from building import *

src = []
path = []
cwd = GetCurrentDir()

# Define wifi host driver paths
whd = 'wifi-host-driver'
whd_path = cwd + '/' + whd
if GetDepend(['WHD_USING_WIFI6']):
    wifi_standard = 'COMPONENT_WIFI6'
else:
    wifi_standard = 'COMPONENT_WIFI5'
whd_src_path = whd_path + '/WHD' + '/' + wifi_standard
whd_src_path_prefix = whd + '/WHD' + '/' + wifi_standard

# Add the general drivers.
src += Glob(whd_src_path_prefix + '/src/bus_protocols/whd_bus_common.c')
src += Glob(whd_src_path_prefix + '/src/bus_protocols/whd_bus_sdio_protocol.c')
src += Glob(whd_src_path_prefix + '/src/bus_protocols/whd_bus.c')

# Add wifi host driver source and header files
src += Glob(whd_src_path_prefix + '/src/*.c')
path += [whd_src_path + '/src']
path += [whd_src_path + '/inc']
path += [whd_src_path + '/src/include']
path += [whd_src_path + '/src/bus_protocols']
path += [whd_src_path + '/resources/resource_imp']

# Add wifi host driver porting source and header files
src += Glob('porting/src/bsp/*.c')
src += Glob('porting/src/wlan/*.c')
src += Glob('porting/src/resources/*.c')

if GetDepend(['WHD_RESOURCES_IN_MEMORY']):
    if GetDepend(['WHD_USING_CHIP_CYW55500']):
        resources_dir = os.path.abspath(os.path.join(cwd, '..', '..', '..', 'resources'))
        firmware_file = os.path.join(resources_dir, '55500A1.trxcse')
        clm_file = os.path.join(resources_dir, '55500A1.clm_blob')
        nvram_file = os.path.join(resources_dir, 'cyw55513modpse84som_rev3.txt')

        for item in [firmware_file, clm_file, nvram_file]:
            if not os.path.isfile(item):
                raise RuntimeError('Missing WHD resource file: ' + item)

        def _c_array_bytes(data):
            lines = []
            for offset in range(0, len(data), 16):
                lines.append('    ' + ', '.join([str(b) for b in bytearray(data[offset:offset + 16])]))
            return ',\n'.join(lines)

        def _generate_whd_resources(target, source, env):
            firmware = open(str(source[0]), 'rb').read()
            clm = open(str(source[1]), 'rb').read()
            nvram = open(str(source[2]), 'rb').read()
            nvram = nvram.replace(b'\r\n', b'\n').replace(b'\r', b'\n').replace(b'\n', b'\x00')
            if len(nvram) == 0 or nvram[-1] != 0:
                nvram += b'\x00'

            output = '''#include <stdint.h>
#include "wiced_resource.h"

#if defined(CY_STORAGE_WIFI_DATA)
CY_SECTION_WHD(CY_STORAGE_WIFI_DATA) __attribute__((used))
#endif
const unsigned char wifi_firmware_image_data[{firmware_size}] = {{
{firmware_data}
}};

const resource_hnd_t wifi_firmware_image = {{ RESOURCE_IN_MEMORY, {firmware_size}, {{.mem = {{(const char *)wifi_firmware_image_data}}}} }};

#if defined(CY_STORAGE_WIFI_DATA)
CY_SECTION_WHD(CY_STORAGE_WIFI_DATA) __attribute__((used))
#endif
const unsigned char wifi_firmware_clm_blob_data[{clm_size}] = {{
{clm_data}
}};

const resource_hnd_t wifi_firmware_clm_blob = {{ RESOURCE_IN_MEMORY, {clm_size}, {{.mem = {{(const char *)wifi_firmware_clm_blob_data}}}} }};

const char wifi_nvram_image[{nvram_size}] = {{
{nvram_data}
}};

const uint32_t wifi_nvram_image_size = {nvram_size};
'''.format(
                firmware_size=len(firmware),
                firmware_data=_c_array_bytes(firmware),
                clm_size=len(clm),
                clm_data=_c_array_bytes(clm),
                nvram_size=len(nvram),
                nvram_data=_c_array_bytes(nvram),
            )

            with open(str(target[0]), 'w') as fp:
                fp.write(output)

        generated = env.Command(
            '#build/libraries/components/wifi-host-driver/whd_project_resources.c',
            [firmware_file, clm_file, nvram_file],
            _generate_whd_resources)
        src += generated

if GetDepend(['WHD_PORTING_BSP']):
    path += [cwd + '/porting/inc/bsp']

if GetDepend(['WHD_PORTING_HAL']):
    src += Glob('porting/src/hal/*.c')
    path += [cwd + '/porting/inc/hal']

if GetDepend(['WHD_PORTING_RTOS']):
    src += Glob('porting/src/rtos/*.c')
    path += [cwd + '/porting/inc/rtos']

# RT_USING_WIFI_HOST_DRIVER or PKG_USING_WIFI_HOST_DRIVER
group = DefineGroup('whd', src, depend = ['RT_USING_WIFI_HOST_DRIVER'], CPPPATH = path)
if GetDepend(['PKG_USING_WIFI_HOST_DRIVER']):
    group = DefineGroup('whd', src, depend = ['PKG_USING_WIFI_HOST_DRIVER'], CPPPATH = path)

Return('group')
