
#ifndef RTCONFIG_PREINC_H__
#define RTCONFIG_PREINC_H__

/* Automatically generated file; DO NOT EDIT. */
/* RT-Thread pre-include file */

#define ARM_MATH_AUTOVECTORIZE
#define ARM_MATH_DSP
#define ARM_MATH_HELIUM
#define BLHS_SUPPORT
#define COMPONENT_55500
#define COMPONENT_55500A1
#define COMPONENT_APP_KIT_PSE84_AI
#define COMPONENT_CM55
#define COMPONENT_CM55_0
#define COMPONENT_Debug
#define COMPONENT_GCC_ARM
#define COMPONENT_GFXSS
#define COMPONENT_HARDFP
#define COMPONENT_HCI_UART
#define COMPONENT_ML_INT8x8
#define COMPONENT_ML_TFLM
#define COMPONENT_MTB_DEVICE_SUPPORT
#define COMPONENT_MTB_HAL
#define COMPONENT_MW_ASYNC_TRANSFER
#define COMPONENT_MW_CMSIS
#define COMPONENT_MW_CORE_LIB
#define COMPONENT_MW_CORE_MAKE
#define COMPONENT_MW_MTB_DSL_PSE8XXGP
#define COMPONENT_MW_RETARGET_IO
#define COMPONENT_NON_SECURE_DEVICE
#define COMPONENT_PSE84
#define COMPONENT_RTOS_AWARE
#define COMPONENT_SM
#define COMPONENT_U55
#define CORE_NAME_CM55_0 1
#define CYBSP_MCUBOOT_HEADER_SIZE 0x400
#define CY_APPNAME_proj_cm55
#define CY_PDL_FLASH_BOOT
#define CY_RETARGET_IO_CONVERT_LF_TO_CRLF
#define CY_RTOS_AWARE
#define CY_SRF_DISABLE
#define CY_SUPPORTS_DEVICE_VALIDATION
#define CY_TARGET_BOARD APP_KIT_PSE84_AI
#define DEBUG
#define ETHOSU55
#define FLASH_BOOT
#define MTB_ML_ETHOSU_CACHE_MGMT_TYPE MTB_ML_ETHOSU_CACHE_MGMT_ALL_LAYERS
#define PSE846GPS2DBZC4A
#define RT_USING_LIBC
#define RT_USING_NEWLIBC
#define TARGET_APP_KIT_PSE84_AI
#define TF_LITE_STATIC_MEMORY
#define TRXV5
#define USBH_DISABLE_STANDARD_OUTPUT 1
#define _POSIX_C_SOURCE 1
#define _REENT_SMALL
#define __RTTHREAD__

#endif /*RTCONFIG_PREINC_H__*/
