
#ifndef RTCONFIG_PREINC_H__
#define RTCONFIG_PREINC_H__

/* Automatically generated file; DO NOT EDIT. */
/* RT-Thread pre-include file */

#define BLHS_SUPPORT
#define COMPONENT_APP_KIT_PSE84_AI
#define COMPONENT_CM33
#define COMPONENT_CM33_0
#define COMPONENT_Debug
#define COMPONENT_GCC_ARM
#define COMPONENT_MTB_DEVICE_SUPPORT
#define COMPONENT_MTB_HAL
#define COMPONENT_MW_CMSIS
#define COMPONENT_MW_CORE_LIB
#define COMPONENT_MW_MTB_DSL_PSE8XXGP
#define COMPONENT_NON_SECURE_DEVICE
#define COMPONENT_PSE84
#define COMPONENT_SOFTFP
#define CORE_NAME_CM33_0 1
#define CYBSP_MCUBOOT_HEADER_SIZE 0x400
#define CY_APPNAME_proj_cm33_ns
#define CY_PDL_FLASH_BOOT
#define CY_SRF_DISABLE
#define CY_SUPPORTS_DEVICE_VALIDATION
#define CY_TARGET_BOARD APP_KIT_PSE84_AI
#define DEBUG
#define FLASH_BOOT
#define PSE846GPS2DBZC4A
#define RT_USING_LIBC
#define RT_USING_NEWLIBC
#define TARGET_APP_KIT_PSE84_AI
#define TRXV5
#define _POSIX_C_SOURCE 1
#define __RTTHREAD__

#endif /*RTCONFIG_PREINC_H__*/
