from building import *
import os

cwd = GetCurrentDir()
repository_root = os.path.abspath(os.path.join(cwd, '../../../..'))
LIBS = []
LIBPATH = []
# Add all subdirectories to include path
path = []
path += [cwd]
path += [cwd + '/litegfx/adapt', cwd + '/litegfx/plat', cwd + '/litegfx/vglite/include', cwd + '/sample', cwd + '/sample/lz4', cwd + '/sample/resource/AnimatedEmoji']
path += [repository_root + '/libraries/Common/board/ports/lvgl']
path += [repository_root + '/libraries/HAL_Drivers']
path += [repository_root + '/libraries/components/lvgl_9.2.0/src/draw/vg_lite']
path += [repository_root + '/libraries/components/mtb-device-support-pse8xxgp/pdl/drivers/third_party/COMPONENT_GFXSS']
path += [repository_root + '/libraries/components/mtb-device-support-pse8xxgp/pdl/drivers/third_party/COMPONENT_GFXSS/vsi/gcnano']

src = Glob('*.c') + Glob('*.cpp')
src += Glob('litegfx/adapt/*.c') + Glob('litegfx/plat/*.c') + Glob('litegfx/plat/*.cpp')
src += Glob('sample/*.c') + Glob('sample/lz4/*.c') + Glob('sample/resource/AnimatedEmoji/*.c')
LIBS+= ['lx_vglite']
LIBPATH += [cwd + '/litegfx/vglite']

group = DefineGroup('virtual3d_emoji_3d_demo', src, depend=['BSP_LVGL_DEMO_VIRTUAL3D_EMOJI'], LIBS = LIBS, LIBPATH=LIBPATH, CPPPATH=path)
list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
